"""pousers table

Revision ID: 37584ab88274
Revises: ae346256b650
Create Date: 2022-03-26 17:11:06.857323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37584ab88274'
down_revision = 'ae346256b650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_cat', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('balance', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_user_cat'), 'user', ['user_cat'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_cat'), table_name='user')
    op.drop_column('user', 'balance')
    op.drop_column('user', 'user_cat')
    # ### end Alembic commands ###
