"""orders table add returned

Revision ID: b86e278a456b
Revises: 9b7d675de85b
Create Date: 2022-03-28 11:47:22.692292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86e278a456b'
down_revision = '9b7d675de85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('returned', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'returned')
    # ### end Alembic commands ###
